//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballManager.modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeRoom
    {
        public int ID { get; set; }
        public string RoomNumber { get; set; }
        public Nullable<bool> StatusRoom { get; set; }
        public int StationID { get; set; }
        public Nullable<System.DateTime> StartDateRoom { get; set; }
        public Nullable<System.DateTime> EndDateRoom { get; set; }
    
        public virtual Station Station { get; set; }
    }
}
