//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballManager.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station
    {
        public int ID { get; set; }
        public Nullable<int> StationNumber { get; set; }
        public Nullable<bool> Status { get; set; }
        public int RoomID { get; set; }
        public string Price { get; set; }
    
        public virtual ChangeRoom ChangeRoom { get; set; }
    }
}
